# Jekyll configuration
markdown: kramdown
highlighter: rouge
language: 'en'

# Website info
name: 'Yousef Taheri'
title: 'Yousef Taheri - AI/ML Researcher & Developer'
description: "AI/ML Researcher & Developer specializing in Responsible AI and Ethical Machine Learning"
author: 'Yousef Taheri'
email: 'contact@youseftaheri.com'
url: 'https://heritai.github.io'
baseurl: ''

# Social links
social:
  github: 'heritai'
  linkedin: 'yousef-taheri'
  twitter: 'HeritaMind'
  scholar: 'IN72HckAAAAJ'

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - .git
  - .gitignore
